# Generated by Django 4.2 on 2023-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_informacionpersonal_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
