# Generated by Django 4.2 on 2023-04-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaspirantesmodels',
            name='imagenes',
            field=models.FileField(default=1, upload_to='documento/imagenes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postaspirantesmodels',
            name='pdf',
            field=models.FileField(default=1, upload_to='documento/pdf'),
            preserve_default=False,
        ),
    ]
